apiVersion: v1
kind: Service
metadata:
  name: car-valuation-ai
spec:
  selector:
    app.kubernetes.io/name: car-valuation-ai
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8585

