apiVersion: v1
kind: ConfigMap
metadata:
  name: car-valuation-ai-config
data:
  BASE_URL={BASE_URL}
  AGENT_NAME={AGENT_NAME}
  MODEL_NAME={MODEL_NAME}
  SKILL_LOCATION=skills
  TEMPERATURE={TEMPERATURE}
  MIN_K={MIN_K}
  MIN_P={MIN_P}
  PRESENCE_PENALTY={PRESENCE_PENALTY}
  FREQUENCY_PENALTY={FREQUENCY_PENALTY}
  MAXIMUM_TOKENS={MAXIMUM_TOKENS}
  
