apiVersion: v1
kind: ConfigMap
metadata:
  name: car-valuation-ai-config
data:
  SERVER_HOST: "{SERVER_HOST}"
  SERVER_PORT: "{SERVER_PORT}"
  SERVER_READ_TIMEOUT: "{SERVER_READ_TIMEOUT}"
  SERVER_WRITE_TIMEOUT: "{SERVER_WRITE_TIMEOUT}"
  WAIT_TIMEOUT: "{WAIT_TIMEOUT}"
  BASE_URL: "{BASE_URL}"
  AGENT_NAME: "{AGENT_NAME}"
  MODEL_NAME: "{MODEL_NAME}"
  SKILL_LOCATION: "{SKILL_LOCATION}"
  TEMPERATURE: "{TEMPERATURE}"
  TOP_K: "{TOP_K}"
  TOP_P: "{TOP_P}"
  PRESENCE_PENALTY: "{PRESENCE_PENALTY}"
  FREQUENCY_PENALTY: "{FREQUENCY_PENALTY}"
  MAXIMUM_TOKENS: "{MAXIMUM_TOKENS}"
  
