name: code-review

on:
  workflow_dispatch:
    inputs:
      analysis_type:
        description: "Type of analysis to perform"
        required: true
        type: choice
        options:
          - summarize-commit
        default: "summarize-commit"
jobs:
   code-review:
    permissions:
        packages: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            use `code-reviewer` agent to review this project codebase 

